name: Deploy
on: 
    push:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v4
        - name: install dependencies
          run: pip install -r requirements.txt
        - name: Run security scan with Bandit 
          run: |
            pip install bandit
            bandit -r src -o bandit_report.txt -f txt 
        - name: Upload Bandit scan results
          uses: actions/upload-artifact@v4
          with:
            name: bandit-scan-results
            path: bandit_report.txt
          if: ${{ always() }}
        - name: create Docker image
          run: docker build -t pythonimage .
        - name: run docker image
          run: docker run pythonimage

