on:
    workflow_call: 

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: create Docker image
          run: docker build -t pythonimage .
        - name: run docker image
          run: docker run pythonimage